resources:
  pipelines:
  - pipeline: playwrightPipe   # Name of the pipeline resource
    source: skow0020.qa-library # Name of the pipeline referenced by the pipeline resource
    trigger: 
      branches:
      - master

pool:
  vmImage: 'windows-latest'
      
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.10'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Install base packages'
  inputs:
    command: 'install'

- task: Npm@1
  displayName: 'Run Automation'
  inputs:
    command: custom
    customCommand: 'run test'