resources:
  pipelines:
  - pipeline: playwrightPipe   # Name of the pipeline resource
    source: skow0020.qa-library # Name of the pipeline referenced by the pipeline resource
    trigger: 
      branches:
      - master
      stages:
      - stage: 'runAutomation'
        pool: 
          vmImage: 'Ubuntu-16.04'
        jobs:
        - job: secure_buildjob
          steps:
          - script: echo This happens before code 
            displayName: 'Base: Pre-build'